// 塔罗牌完整数据 - 78张韦特塔罗牌
const TAROT_DATA = {
    // 大阿尔卡纳 (22张)
    majorArcana: [
        { id:0, name:"愚者", nameEn:"The Fool", number:0, arcana:"major", element:"风", astrology:"天王星",
          keywords:["新的开始","冒险","纯真","自由","自发性"],
          uprightMeaning:"代表新的开始、冒险精神和无限可能。你正站在人生的新起点，保持开放的心态，勇敢地迈出第一步。",
          reversedMeaning:"可能表示鲁莽行事、缺乏计划或逃避责任。",
          psychologicalInsight:"愚者代表内在小孩的纯真状态——那种未被社会规训完全塑造的、充满好奇和创造力的自我。它邀请我们重新连接内心深处那个敢于尝试、不怕失败的自己。",
          advice:"相信直觉，但也要做好基本准备。新旅程需要勇气，也需要智慧。",
          symbol:"🃏", color:"#FFFFFF" },
        { id:1, name:"魔术师", nameEn:"The Magician", number:1, arcana:"major", element:"水星", astrology:"水星",
          keywords:["创造力","意志力","技能","显化","行动"],
          uprightMeaning:"你拥有将想法转化为现实的能力。所有资源都已齐备，现在是采取行动的时候了。",
          reversedMeaning:"可能表示才能被浪费、操纵他人或缺乏方向感。",
          psychologicalInsight:"魔术师象征着自我的能动性和效能感——相信自己能够影响环境、实现目标的心理状态。四种元素的统一象征人格整合。",
          advice:"聚焦你的意图，运用你的技能。你有能力创造奇迹。",
          symbol:"🎩", color:"#FFD700" },
        { id:2, name:"女祭司", nameEn:"The High Priestess", number:2, arcana:"major", element:"月亮", astrology:"月亮",
          keywords:["直觉","神秘","内在智慧","潜意识","静默"],
          uprightMeaning:"倾听内心的声音。答案不在外部世界，而在你的内心深处。信任你的直觉，保持耐心和观察。",
          reversedMeaning:"可能表示忽视直觉、过度理性化或隐藏秘密。",
          psychologicalInsight:"女祭司代表潜意识、直觉和内在智慧——那些超越逻辑思维的知识来源。真正的智慧往往来自更深层的内在感知。",
          advice:"安静下来，倾听内心的声音。有些答案只能通过静默获得。",
          symbol:"🌙", color:"#4169E1" },
        { id:3, name:"皇后", nameEn:"The Empress", number:3, arcana:"major", element:"金星", astrology:"金星",
          keywords:["丰饶","母性","创造力","自然","感官享受"],
          uprightMeaning:"丰盛与创造的能量正在流动。这是享受生活、培育项目和关爱他人的好时刻。",
          reversedMeaning:"可能表示创造性受阻、依赖过度或忽视自我照顾。",
          psychologicalInsight:"皇后象征着大母神原型的积极面向——丰饶、滋养、包容的女性力量。提供安全感和无条件的爱。",
          advice:"拥抱生活的美好，培养对自己和他人的温柔关怀。",
          symbol:"👑", color:"#228B22" },
        { id:4, name:"皇帝", nameEn:"The Emperor", number:4, arcana:"major", element:"白羊座", astrology:"白羊座",
          keywords:["权威","结构","父性","稳定","领导力"],
          uprightMeaning:"建立秩序和结构的时刻。通过纪律和权威来达成目标。展现领导力，承担责任。",
          reversedMeaning:"可能表示专制、僵化或缺乏控制力。",
          psychologicalInsight:"皇帝代表父性原则——规则、秩序、边界和保护。健康的皇帝能量提供安全感和稳定性。",
          advice:"建立清晰的结构和边界，但保持心胸开放。",
          symbol:"🏛️", color:"#8B0000" },
        { id:5, name:"教皇", nameEn:"The Hierophant", number:5, arcana:"major", element:"金牛座", astrology:"金牛座",
          keywords:["传统","信仰","教育","精神指引"],
          uprightMeaning:"寻求传统智慧或精神指引的时刻。学习、教导或遵循既定道路会带来益处。",
          reversedMeaning:"可能表示挑战传统、非正统信念或个人与群体的冲突。",
          psychologicalInsight:"教皇代表文化传承、集体价值观和精神寻求的社会维度。涉及文化认同和社会化过程。",
          advice:"尊重智慧的传统，同时保持个人真理的完整性。",
          symbol:"⛪", color:"#800080" },
        { id:6, name:"恋人", nameEn:"The Lovers", number:6, arcana:"major", element:"双子座", astrology:"双子座",
          keywords:["爱","选择","和谐","价值观","吸引力"],
          uprightMeaning:"重要的选择摆在面前，通常涉及人际关系或价值取向。追随内心真实的渴望。",
          reversedMeaning:"可能表示选择困难、价值观冲突或关系中的不平衡。",
          psychologicalInsight:"恋人牌不仅关于浪漫爱情，更深刻地关乎整合与选择。每一次重要的人生选择都是一次整合的机会。",
          advice:"做出忠于自己的选择。真正的爱始于自爱。",
          symbol:"💕", color:"#FF69B4" },
        { id:7, name:"战车", nameEn:"The Chariot", number:7, arcana:"major", element:"巨蟹座", astrology:"巨蟹座",
          keywords:["意志力","胜利","决心","控制","进取"],
          uprightMeaning:"通过坚定的意志力取得成功。克服障碍，朝着目标前进。掌控局面。",
          reversedMeaning:"可能表示失去控制、方向混乱或侵略性过强。",
          psychologicalInsight:"战车代表自我效能感和意志力的胜利——相信自己有能力克服挑战并达成目标的信念。",
          advice:"保持专注，用意志力驾驭各种力量为你服务。",
          symbol:"⚔️", color:"#FF4500" },
        { id:8, name:"力量", nameEn:"Strength", number:8, arcana:"major", element:"狮子座", astrology:"狮子座",
          keywords:["勇气","耐心","内在力量","慈悲","自制"],
          uprightMeaning:"真正的力量来自内心的平静和耐心。以柔克刚，用爱和勇气面对挑战。",
          reversedMeaning:"可能表示自我怀疑、失去信心或使用错误的方式处理问题。",
          psychologicalInsight:"力量牌展示了一种不同于外在征服的内在力量——通过接纳、耐心和温柔来转化恐惧和攻击性。",
          advice:"温柔本身就是最强大的力量。相信你内在的能力。",
          symbol:"🦁", color:"#FFA500" },
        { id:9, name:"隐士", nameEn:"The Hermit", number:9, arcana:"major", element:"处女座", astrology:"处女座",
          keywords:["独处","内省","指引","寻找真理"],
          uprightMeaning:"一段内省和独处的时期。寻找内在的真理，或者寻求智慧的导师。暂时退后是为了更好地前进。",
          reversedMeaning:"可能表示孤立、拒绝帮助或迷失方向。",
          psychologicalInsight:"隐士代表独处和内省的价值——在喧嚣的世界中找到与自己相处的空间。高质量的独处时间对创造力和情绪恢复至关重要。",
          advice:"享受独处的时间，那是灵魂成长的最佳土壤。",
          symbol:"🏔️", color:"#708090" },
        { id:10, name:"命运之轮", nameEn:"Wheel of Fortune", number:10, arcana:"major", element:"木星", astrology:"木星",
          keywords:["命运","循环","转折点","好运","变化"],
          uprightMeaning:"命运之轮正在转动，变化即将到来。这可能是一个幸运的转折点。适应变化，把握机遇。",
          reversedMeaning:"可能表示抗拒改变、坏运气或打破循环的困难。",
          psychologicalInsight:"命运之轮提醒我们生活中循环变化的本质——没有什么是永恒的。接受变化而非抵抗它，是心理韧性的重要组成部分。",
          advice:"顺应生命的流转。每一个结束都是新的开始。",
          symbol:"🎡", color:"#9400D3" },
        { id:11, name:"正义", nameEn:"Justice", number:11, arcana:"major", element:"天秤座", astrology:"天秤座",
          keywords:["公正","真相","因果","责任","平衡"],
          uprightMeaning:"公正的结果即将到来。为自己的决定负责，寻求公平和平衡。",
          reversedMeaning:"可能表示不公、逃避责任或偏见。",
          psychologicalInsight:"正义牌触及道德发展和责任感这一核心心理主题。成熟的道德判断基于原则而非功利。",
          advice:"诚实面对自己和他人。因果法则始终在运作。",
          symbol:"⚖️", color:"#4B0082" },
        { id:12, name:"倒吊人", nameEn:"The Hanged Man", number:12, arcana:"major", element:"海王星", astrology:"海王星",
          keywords:["暂停","牺牲","新视角","放下","等待"],
          uprightMeaning:"一个暂停和等待的时期。换个角度看问题，可能会有全新的发现。有时候放手才能得到更多。",
          reversedMeaning:"可能表示拖延、无谓的牺牲或拒绝改变视角。",
          psychologicalInsight:"倒吊人是关于范式转换和认知重构的牌。当你颠倒看世界时，一切都变得不同了。",
          advice:"放下控制，允许事情以它们自己的方式展开。",
          symbol:"🔄", color:"#006400" },
        { id:13, name:"死神", nameEn:"Death", number:13, arcana:"major", element:"天蝎座", astrology:"天蝎座",
          keywords:["结束","转变","重生","过渡","释放"],
          uprightMeaning:"重大的转变和结束。旧的事物必须消亡，新的才能诞生。这是一张关于蜕变的牌，而非字面意义上的死亡。",
          reversedMeaning:"可能表示抗拒改变、停滞不前或无法放下过去。",
          psychologicalInsight:"死神牌是关于心理蜕变和转化的核心意象。旧的身份、模式、关系的终结，为新事物的出现腾出空间。",
          advice:"拥抱结束，因为每个终点都是新起点的伪装。",
          symbol:"☠️", color:"#000000" },
        { id:14, name:"节制", nameEn:"Temperance", number:14, arcana:"major", element:"射手座", astrology:"射手座",
          keywords:["平衡","适度","耐心","融合","中庸之道"],
          uprightMeaning:"找到平衡与和谐。不同的元素在你生命中融合，创造出美好的结果。保持耐心和中庸之道。",
          reversedMeaning:"可能表示失衡、过度或缺乏和谐。",
          psychologicalInsight:"节制牌描绘的是心理整合的过程——将对立面融合为更高层次的统一。在各种极端之间找到动态平衡的中道。",
          advice:"在极端之间寻找中间道路。平衡是持久幸福的秘诀。",
          symbol:"🌈", color:"#20B2AA" },
        { id:15, name:"恶魔", nameEn:"The Devil", number:15, arcana:"major", element:"摩羯座", astrology:"摩羯座",
          keywords:["束缚","诱惑","物质主义","阴影","成瘾"],
          uprightMeaning:"审视那些束缚你的东西——可能是成瘾、不健康的关系或消极的思维模式。意识到束缚是解脱的第一步。",
          reversedMeaning:"可能表示正在挣脱束缚、面对阴影或发现隐藏的真相。",
          psychologicalInsight:"恶魔牌直接指向荣格心理学中的'阴影'——那些我们否认、压抑或不愿承认的自我部分。觉知是自由的开始。",
          advice:"正视那些让你感到被困住的东西。觉知是自由的开始。",
          symbol:"⛓️", color:"#3D0C02" },
        { id:16, name:"高塔", nameEn:"The Tower", number:16, arcana:"major", element:"火星", astrology:"火星",
          keywords:["突变","崩塌","觉醒","启示","解放"],
          uprightMeaning:"突然的、剧烈的变化。虚假的结构崩塌，虽然痛苦却是必要的。真相大白，重建的基础更加坚实。",
          reversedMeaning:"可能表示避免灾难、内在变革或延迟的崩溃。",
          psychologicalInsight:"高塔代表创伤性的突破时刻。虽然经历高塔事件极其痛苦，但它往往带来必要的觉醒和成长。",
          advice:"当旧的结构崩塌时，记住：废墟之下是新生活的地基。",
          symbol:"⚡", color:"#2F4F4F" },
        { id:17, name:"星星", nameEn:"The Star", number:17, arcana:"major", element:"水瓶座", astrology:"水瓶座",
            keywords:["希望","灵感","宁静","治愈","信仰"],
            uprightMeaning:"风暴过后的希望与平静。治愈的能量正在流入你的生活。保持对未来的信心和乐观。",
            reversedMeaning:"可能表示绝望、断连或缺乏信仰。",
            psychologicalInsight:"星星牌出现在高塔之后绝非偶然——它代表创伤后的修复与希望。这对应着'希望'和'乐观'这两种核心优势。",
            advice:"让希望的星光指引你穿越黑暗。治愈正在进行中。",
            symbol:"⭐", color:"#1E90FF" },
        { id:18, name:"月亮", nameEn:"The Moon", number:18, arcana:"major", element:"双鱼座", astrology:"双鱼座",
            keywords:["幻觉","恐惧","直觉","潜意识","不安"],
            uprightMeaning:"事物并不像表面看起来那样。面对内心的恐惧和不安全感。信任直觉，但要警惕欺骗。",
            reversedMeaning:"可能表示释放恐惧、真相浮现或走出困惑。",
            psychologicalInsight:"月亮牌探索的是心灵中那些模糊、不确定、令人不安的领域——焦虑、恐惧、幻觉、梦境。",
            advice:"不要害怕黑暗。月光下，即使是恐惧也能教会我们重要的东西。",
            symbol:"🌕", color:"#191970" },
        { id:19, name:"太阳", nameEn:"The Sun", number:19, arcana:"major", element:"太阳", astrology:"太阳",
            keywords:["快乐","成功","活力","乐观","真相大白"],
            uprightMeaning:"纯粹的喜悦和成功。一切都在光明之中，能量充沛，乐观向上。这是生命中最美好的时刻之一。",
            reversedMeaning:"可能表示暂时的挫折、过度乐观或内在小孩需要关注。",
            psychologicalInsight:"太阳是整个塔罗牌组中最积极的牌之一，代表心理健康的理想状态：活力、喜悦、真实和自发性。",
            advice:"尽情享受这份光明。你是值得被爱的，生活是美好的。",
            symbol:"☀️", color:"#FFD700" },
        { id:20, name:"审判", nameEn:"Judgement", number:20, arcana:"major", element:"冥王星", astrology:"冥王星",
            keywords:["重生","召唤","内心呼唤","宽恕","觉醒"],
            uprightMeaning:"精神的觉醒和召唤。回顾过去，做出评判，然后原谅自己和他人。这是更高层面的重生。",
            reversedMeaning:"可能表示自我怀疑、拒绝召唤或无法原谅。",
            psychologicalInsight:"审判牌描绘的是一种深刻的自我反思和觉醒时刻——听到内心深处的召唤，重新评估自己的人生选择。",
            advice:"聆听内心的召唤。是时候活出真正的自己了。",
            symbol:"📯", color:"#E6E6FA" },
        { id:21, name:"世界", nameEn:"The World", number:21, arcana:"major", element:"土星", astrology:"土星",
            keywords:["完成","成就","整合","旅行","圆满"],
            uprightMeaning:"一个重要周期的圆满完成。成就感、整合和庆祝的时刻。你已经学到了需要学习的一切。",
            reversedMeaning:"可能表示未完成的周期、延迟或寻求闭合。",
            psychologicalInsight:"世界牌代表个体化过程的圆满完成——整合意识与潜意识的所有方面，成为一个完整的、独特的个体。",
            advice:"庆祝你的成就。每个终点都是通往更广阔世界的门。",
            symbol:"🌍", color:"#00CED1" }
    ],

    // 小阿尔卡纳 - 权杖 (火元素) 14张
    wands: [
        { id:22, name:"权杖首牌", nameEn:"Ace of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["新机会","灵感","热情","创造力","开始"],
          uprightMeaning:"新的创意火花或机会出现。充满激情和动力去开启新项目。这是行动的信号！",
          reversedMeaning:"延误、缺乏动力或错失机会。",
          psychologicalInsight:"权杖首牌代表内在动机和创造冲动的迸发——那种'我有一个绝妙主意'的兴奋感。这与内在动机和创新思维密切相关。",
          advice:"抓住灵感的火花，让它燃烧成燎原之火。",
          symbol:"🔥", color:"#FF6347" },
        { id:23, name:"权杖二", nameEn:"Two of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["规划","决策","展望","大胆","未来"],
          uprightMeaning:"站在成功的门槛上，展望更广阔的未来。是时候做出大胆的决定并规划下一步了。",
          reversedMeaning:"恐惧未知、缺乏规划或停留在舒适区。",
          psychologicalInsight:"权杖二描绘了站在已有成就的基础上展望未来的时刻——这涉及前瞻性思维和规划能力。",
          advice:"勇敢地眺望远方。你的视野决定了你能走多远。",
          symbol:"🔥", color:"#FF6347" },
        { id:24, name:"权杖三", nameEn:"Three of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["扩张","前景","合作","远见","等待成果"],
          uprightMeaning:"你的努力正在开花结果。展望更广阔的前景，扩张的机会正在到来。",
          reversedMeaning:"障碍、缺乏进展或挫折。",
          psychologicalInsight:"权杖三代表播种后等待收获的阶段——这考验着我们的延迟满足能力和对未来回报的信念。",
          advice:"保持远见。你播下的种子正在生长。",
          symbol:"🔥", color:"#FF6347" },
        { id:25, name:"权杖四", nameEn:"Four of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["庆祝","和谐","家庭","稳定","欢乐"],
          uprightMeaning:"庆祝和欢乐的时刻。家庭和睦、事业稳固，是享受成果的时候。",
          reversedMeaning:"过渡期、不稳定或缺乏和谐。",
          psychologicalInsight:"权杖四描绘了社区庆典和家庭团聚的场景——这代表归属感和社会支持的重要性。",
          advice:"停下来庆祝你的成就。幸福在于分享。",
          symbol:"🔥", color:"#FF6347" },
        { id:26, name:"权杖五", nameEn:"Five of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["冲突","竞争","分歧","挑战","张力"],
          uprightMeaning:"面临竞争或冲突。不同观点的碰撞可能导致建设性的讨论，也可能引发不必要的争斗。",
          reversedMeaning:"避免冲突、内部冲突或寻找解决方案。",
          psychologicalInsight:"权杖五展示了竞争心理和群体动力学。建设性的冲突可以促进创新和更好的决策。",
          advice:"将竞争转化为成长的燃料。不是所有的冲突都是坏事。",
          symbol:"🔥", color:"#FF6347" },
        { id:27, name:"权杖六", nameEn:"Six of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["胜利","认可","自信","荣耀","公众认可"],
          uprightMeaning:"胜利和公众认可的到来。你的努力得到了肯定，自信心高涨。",
          reversedMeaning:"自我膨胀、失宠或缺乏认可。",
          psychologicalInsight:"权杖六描绘了胜利者的凯旋——这涉及成就动机和社会认可的心理需求。",
          advice:"享受你的胜利时刻，但保持谦逊。",
          symbol:"🔥", color:"#FF6347" },
        { id:28, name:"权杖七", nameEn:"Seven of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["防御","坚持","勇气","立场","逆境"],
          uprightMeaning:"处于防御位置，坚守自己的立场。面对挑战时不退缩，维护自己的成果。",
          reversedMeaning:"放弃、不堪重负或孤立无援。",
          psychologicalInsight:"权杖七显示了一个人在高地上抵御众多对手——这代表了心理韧性和抗压能力。",
          advice:"坚守阵地。你有能力捍卫你认为正确的事情。",
          symbol:"🔥", color:"#FF6347" },
        { id:29, name:"权杖八", nameEn:"Eight of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["速度","进展","行动","消息","快速移动"],
          uprightMeaning:"事情迅速发展。好消息传来，项目快速推进。行动的时机到了！",
          reversedMeaning:"延误、挫败或精力分散。",
          psychologicalInsight:"权杖八展示权杖在空中飞驰——这代表加速和势能。关键是确保速度不会牺牲质量。",
          advice:"顺势而为，让事情快速发展。",
          symbol:"🔥", color:"#FF6347" },
        { id:30, name:"权杖九", nameEn:"Nine of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["坚韧","警觉","疲惫","毅力","最后防线"],
          uprightMeaning:"经历了漫长的战斗，但你依然站立。保持警惕和坚韧，胜利就在眼前。",
          reversedMeaning:"精疲力竭、偏执或过早放弃。",
          psychologicalInsight:"权杖九显示一个受伤但仍然警戒的战士——这完美诠释了'坚毅'(grit)这一心理特质。",
          advice:"你最艰难的战斗已经过去了。坚持下去。",
          symbol:"🔥", color:"#FF6347" },
        { id:31, name:"权杖十", nameEn:"Ten of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["负担","责任","辛苦工作","过度承诺","压力"],
          uprightMeaning:"承担了过多的责任和负担。你可能正在透支自己，需要学会授权和说'不'。",
          reversedMeaning:"卸下重担、委托他人或崩溃。",
          psychologicalInsight:"权杖十描绘了一个背负过多权杖的人——这是职业倦怠(burnout)的经典意象。",
          advice:"你不必独自承担一切。学会放下一些重担。",
          symbol:"🔥", color:"#FF6347" },
        { id:32, name:"权杖侍从", nameEn:"Page of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["探索","好奇心","新消息","热情","发现"],
          uprightMeaning:"充满好奇和探险精神的年轻人。新的消息或机会正在到来，保持开放的心态。",
          reversedMeaning:"坏消息、缺乏方向或冲动行为。",
          psychologicalInsight:"权杖侍从代表发展中的人格面貌——好奇、热情、愿意探索新事物。",
          advice:"保持好奇心。每一个发现都可能改变你的轨迹。",
          symbol:"🔥", color:"#FF6347" },
        { id:33, name:"权杖骑士", nameEn:"Knight of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["冒险","冲动","热情","行动","旅行"],
          uprightMeaning:"充满激情和冒险精神的行动派。变化和旅行可能即将来临。",
          reversedMeaning:"鲁莽、挫败或食言。",
          psychologicalInsight:"权杖骑士代表行动导向、充满激情的人格类型——优点是果断和有活力，缺点可能是冲动。",
          advice:"让你的激情驱动你，但别忘了带上方向盘。",
          symbol:"🔥", color:"#FF6347" },
        { id:34, name:"权杖王后", nameEn:"Queen of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["自信","魅力","独立","热情","领导力"],
          uprightMeaning:"充满魅力和自信的女性形象。独立、热情、有领导力，能够激励他人。",
          reversedMeaning:"嫉妒、不安全感或苛求的行为。",
          psychologicalInsight:"权杖王后代表成熟女性能量的火元素表达——自信、有魅力、独立且富有感染力。",
          advice:"相信你的光芒。你的自信会照亮周围的人。",
          symbol:"🔥", color:"#FF6347" },
        { id:35, name:"权杖国王", nameEn:"King of Wands", arcana:"minor", suit:"wands", suitName:"权杖", element:"火",
          keywords:["愿景","领导","企业家","大胆","灵感"],
          uprightMeaning:"有远见卓识的领导者。天生的企业家，能够激励团队并实现宏伟目标。",
          reversedMeaning:"冲动、暴政或不切实际的期望。",
          psychologicalInsight:"权杖国王代表成熟男性能量的火元素表达——有远见、有魅力、有领导力的领导者原型。",
          advice:"用你的愿景点燃他人的激情。真正的领导者创造更多的领导者。",
          symbol:"🔥", color:"#FF6347" }
    ],

    // 小阿尔卡纳 - 圣杯 (水元素) 14张
    cups: [
        { id:36, name:"圣杯首牌", nameEn:"Ace of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:"水",
          keywords:["新情感","爱","直觉","同情心","情感丰富"],
          uprightMeaning:"新的情感开始。爱情、友谊或创意灵感的涌动。打开心扉，迎接爱与美好。",
          reversedMeaning:"情感阻塞、空虚或悲伤。",
          psychologicalInsight:"圣杯首牌代表情感的充盈和爱的流动——这是依恋安全和情感能量的源泉。",
          advice:"敞开你的心。爱正在流向你，也流经你。",
          symbol:"💧", color:"#4169E1" },
        { id:37, name:"圣杯二", nameEn:"Two of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:"水",
          keywords:["伴侣关系","相互吸引","连接","结合","爱"],
          uprightMeaning:"相互吸引和深层连接。爱情、伙伴关系或任何形式的深度联结正在形成。",
          reversedMeaning:"不平衡、分手或价值观不一致。",
          psychologicalInsight:"圣杯二描绘了两个人之间的平等交换和相互承诺——健康关系的核心要素：互惠性和深层情感连接。",
          advice:"珍视真正与你产生共鸣的人。好的关系是双向奔赴的。",
          symbol:"💧", color:"#4169E1" },
        { id:38, name:"圣杯三", nameEn:"Three of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:"水",
          keywords:["友谊","庆祝","社区","分享","欢乐"],
          uprightMeaning:"朋友聚会和社交欢乐的时刻。庆祝、分享和社区归属感带来满足。",
          reversedMeaning:"孤立、流言蜚语或过度放纵。",
          psychologicalInsight:"圣杯三展示三个女人一起庆祝——友谊和社会支持的愉悦。归属感是人类的基本心理需求。",
          advice:"珍惜你的朋友圈。分享快乐会让快乐加倍。",
          symbol:"💧", color:"#4169E1" },
        { id:39, name:"圣杯四", nameEn:"Four of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:"水",
          keywords:["冷漠","沉思","冷漠","重新评估","错失良机"],
          uprightMeaning:"对现有的选项感到不满或冷漠。可能错过了近在手边的机会。需要重新评估什么才是真正重要的。",
          reversedMeaning:"觉醒、新视角或摆脱困境。",
          psychologicalInsight:"圣杯四显示一个人对递来的杯子无动于衷——这描绘了情感麻木或享乐适应的现象。",
          advice:"看看你身边已经被忽视的美好。感恩能唤醒沉睡的心。",
          symbol:"💧", color:"#4169E1" },
        { id:40, name:"圣杯五", nameEn:"Five of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:"水",
          keywords:["失落","后悔","失望","悲伤","专注于失去"],
          uprightMeaning:"专注于失去的东西，忽视了还拥有的。失望和悲伤笼罩着你。",
          reversedMeaning:"接受损失、走出阴霾或看到希望。",
          psychologicalInsight:"圣杯五描绘了哀伤的过程——三个人们只关注打翻的杯子，而忽略了完好的两杯。这涉及负面偏差的认知倾向。",
          advice:"不要只盯着失去的东西。转身看看你还拥有什么。",
          symbol:"💧", color:"#4169E1" },
        { id:41, name:"圣杯六", nameEn:"Six of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:"水",
          keywords:["童年","怀旧","回忆","纯真","善意"],
          uprightMeaning:"怀旧和童年回忆涌现。来自过去的礼物或重逢。纯真和善意的回归。",
          reversedMeaning:"沉溺过去、无法前行或幼稚行为。",
          psychologicalInsight:"圣杯六涉及记忆、怀旧和内在小孩的主题。健康的怀旧可以提供安慰和身份认同感。",
          advice:"让童年的纯真滋养你的现在，但不要活在过去。",
          symbol:"💧", color:"#4169E1" },
        { id:42, name:"圣杯七", nameEn:"Seven of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:"水",
          keywords:[" choices","幻想","幻觉","梦想","选项"],
          uprightMeaning:"面临多种选择，但并非所有选项都是真实的。需要辨别幻想与现实。",
          reversedMeaning:"做出决定、清醒过来或清晰的洞察。",
          psychologicalInsight:"圣杯七展示了七个漂浮的杯子——这反映了决策过程中的认知 overload 和选择困难。",
          advice:"不要被太多的选择迷惑。聚焦于真正重要的东西。",
          symbol:"💧", color:"#4169E1" },
        { id:43, name:"圣杯八", nameEn:"Eight of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:"水",
          keywords:["离开","追寻","放弃","转变"," quest"],
          uprightMeaning:"离开不再服务于你的事物。一场心灵之旅的开始。有意识地选择离开舒适区。",
          reversedMeaning:" fear of change, stuck in rut or avoiding necessary departure.",
          psychologicalInsight:"圣杯八描绘了一个人转身离开一堆杯子——这代表有意识的放手和向更高意义追寻的勇气。",
          advice:"有时候离开是最勇敢的选择。相信你的内心知道何时该走。",
          symbol:"💧", color:"#4169E1" },
        { id:44, name:"圣杯九", nameEn:"Nine of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:"水",
          keywords:["满足","愿望成真"," contentment"," luxury"," emotional fulfillment"],
          uprightMeaning:"通常被称为'许愿牌'。情感上的满足和愿望的实现。享受当下的幸福。",
          reversedMeaning:" dissatisfaction, greed or lack of gratitude.",
          psychologicalInsight:"圣杯九被称为'许愿牌'——这涉及主观幸福感和感恩练习的力量。满足感来自于珍惜已有的东西。",
          advice:"你的愿望正在实现。学会欣赏和感恩你所拥有的。",
          symbol:"💧", color:"#4169E1" },
        { id:45, name:"圣杯十", nameEn:"Ten of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:"水",
          keywords:[" family happiness"," harmony"," blessing"," joyous ending"," emotional completion"],
          uprightMeaning:"终极的情感满足。家庭和睦、关系和谐，所有情感愿望都已实现。",
          reversedMeaning:" family discord, broken dreams or misaligned values.",
          psychologicalInsight:"圣杯十描绘了一家人在彩虹下拥抱——这代表马斯洛需求层次中归属感和爱的最高实现形式。",
          advice:"真正的幸福在于与所爱之人共享生命的美好。",
          symbol:"💧", color:"#4169E1" },
        { id:46, name:"圣杯侍从", nameEn:"Page of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:" water",
          keywords:[" creativity"," intuition"," new emotions"," messenger"," sensitivity"],
          uprightMeaning:"充满想象力和敏感度的年轻人。创意灵感或直觉信息的到来。保持开放和好奇。",
          reversedMeaning:" creative block, immaturity or emotional immaturity.",
          psychologicalInsight:"圣杯侍从代表发展中的人格面貌——富有想象力、敏感、善于接收直觉信息。",
          advice:"倾听你内心的声音。创意和灵感正在靠近。",
          symbol:"💧", color:"#4169E1" },
        { id:47, name:"圣杯骑士", nameEn:"Knight of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:" water",
          keywords:["浪漫","邀请"," charm"," imagination"," idealism"],
          uprightMeaning:"浪漫和理想主义的追求者。一个邀请或提议可能到来。跟随心的引导。",
          reversedMeaning:" moodiness, disappointment or unrealistic expectations.",
          psychologicalInsight:"圣杯骑士代表浪漫、富有想象力的人格类型——优点是富有同理心和艺术气质，缺点可能是过度理想化。",
          advice:"让你的心引领方向，但也要脚踏实地。",
          symbol:"💧", color:"#4169E1" },
        { id:48, name:"圣杯王后", nameEn:"Queen of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:" water",
          keywords:[" compassion"," nurturing"," intuition"," emotional security"," empathy"],
          uprightMeaning:"充满同情心和直觉力的女性形象。情感上的安全港湾，能够深度理解和关怀他人。",
          reversedMeaning:" dependency, martyrdom or emotional manipulation.",
          psychologicalInsight:"圣杯王后代表成熟女性能量的水元素表达——富有同情心、直觉敏锐、情感成熟且具有疗愈力。",
          advice:"你的同理心是你最大的天赋。用它来温暖自己和他人。",
          symbol:"💧", color:"#4169E1" },
        { id:49, name:"圣杯国王", nameEn:"King of Cups", arcana:"minor", suit:"cups", suitName:"圣杯", element:" water",
          keywords:[" emotional balance"," compassion with authority"," diplomacy"," wisdom"],
          uprightMeaning:"情感成熟的领导者。平衡理性与情感，用智慧和同情心来引导他人。",
          reversedMeaning:" moodiness, manipulation or emotional volatility.",
          psychologicalInsight:"圣杯国王代表成熟男性能量的水元素表达——情感稳定、富有同情心、兼具权威与温柔。",
          advice:"真正的力量包含温柔。用智慧平衡你的心与脑。",
          symbol:"💧", color:"#4169E1" }
    ],

    // 小阿尔卡纳 - 宝剑 (风元素) 14张
    swords: [
        { id:50, name:"宝剑首牌", nameEn:"Ace of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" clarity"," breakthrough"," truth"," intellect"," new ideas"],
          uprightMeaning:"思维的突破！真相大白，困惑消除。新的想法和清晰的洞察力到来。",
          reversedMeaning:" confusion, mental blocks or misuse of power.",
          psychologicalInsight:"宝剑首牌代表认知突破和心智清晰——那种拨开迷雾、看清真相的顿悟时刻。",
          advice:"真理之剑正在劈开迷雾。信任你的理智和判断力。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:51, name:"宝剑二", nameEn:"Two of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" indecision"," blocked emotions"," stalemate"," blindfolded choice"],
          uprightMeaning:"难以做决定。可能在回避某些不愿面对的事情。情感上处于僵持状态。",
          reversedMeaning:" information revealed, decision made or releasing indecision.",
          psychologicalInsight:"宝剑二描绘了蒙眼持双剑的女性——这代表决策瘫痪和情感回避的心理状态。",
          advice:"摘下眼罩，直面真相。延迟决定本身也是一种决定。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:52, name:"宝剑三", nameEn:"Three of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" heartbreak"," sorrow"," grief"," pain"," betrayal"],
          uprightMeaning:"心碎和深深的悲伤。痛苦的觉醒，但也是疗愈的必要过程。",
          reversedMeaning:" recovery, forgiveness or pain easing.",
          psychologicalInsight:"宝剑三描绘了心被三把剑穿透——这是丧失和心碎的经典意象。哀伤是愈合的必经之路。",
          advice:"允许自己感受痛苦。伤口会愈合，心会变得更强大。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:53, name:"宝剑四", nameEn:"Four of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" rest"," retreat"," contemplation"," recovery"," solitude"],
          uprightMeaning:"需要休息和恢复的时期。暂时退下来，进行反思和充电。",
          reversedMeaning:" returning to action, restlessness or overexertion.",
          psychologicalInsight:"宝剑四描绘了墓碑前躺着的战士——这强调了主动休息和心理恢复的重要性。",
          advice:"休息不是软弱，而是智慧的体现。给自己喘息的空间。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:54, name:"宝剑五", nameEn:"Five of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" conflict"," empty victory"," defeat"," rivalry"," tension"],
          uprightMeaning:"表面上的胜利实际上是空洞的。冲突之后没有人真正赢家。需要反思竞争的代价。",
          reversedMeaning:" reconciliation, letting go of conflict or seeking peace.",
          psychologicalInsight:"宝剑五展示了一个人收集武器而他人离去——这涉及'皮洛士式胜利'的心理学：赢了战斗却输了关系。",
          advice:"问问自己：赢得争论值得失去关系吗？",
          symbol:"⚔️", color:"#87CEEB" },
        { id:55, name:"宝剑六", nameEn:"Six of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" transition"," journey away"," refuge"," moving on"," calm after storm"],
          uprightMeaning:"从困难处境中过渡到更好的地方。风暴过后的平静旅程，虽然带着忧伤但方向是正确的。",
          reversedMeaning:" resistance to change, stuck in past or unresolved baggage.",
          psychologicalInsight:"宝剑六描绘了摆渡人载着乘客渡河——这代表从痛苦情境中有意识地向更健康状态过渡的过程。",
          advice:"风暴已经过去，前方是平静的水域。继续前行。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:56, name:"宝剑七", nameEn:"Seven of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" strategy"," deception"," stealth"," trickery"," acting alone"],
          uprightMeaning:"需要策略性思考的时刻。可能需要走非常规路线或保持某些信息不公开。",
          reversedMeaning:" confession, apology or coming clean.",
          psychologicalInsight:"宝剑七显示一个人偷偷拿走几把剑——这涉及策略、欺骗和道德灰色地带的心理决策。",
          advice:"有时候最聪明的策略不是正面交锋。但记住：诚实通常是长期的最佳策略。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:57, name:"宝剑八", nameEn:"Eight of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" self-imposed restriction"," imprisonment"," feeling trapped"," victim mentality"],
          uprightMeaning:"感觉自己被困住，但束缚往往是心理上的而非真实的。你的思维模式正在限制你。",
          reversedMeaning:" self-liberation, taking responsibility or freeing mind.",
          psychologicalInsight:"宝剑八描绘了被蒙眼绑缚但周围剑并未真正封锁的人——这完美诠释了'心理监狱'的概念。",
          advice:"最大的牢笼是你自己的心智。你比你想象的更自由。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:58, name:"宝剑九", nameEn:"Nine of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" anxiety"," nightmares"," guilt"," fear"," despair"],
          uprightMeaning:"焦虑和失眠困扰着你。内心的恐惧和担忧在深夜被放大。需要面对和处理这些恐惧。",
          reversedMeaning:" recovery from anxiety, hope returning or seeking help.",
          psychologicalInsight:"宝剑九显示一个人在床上辗转反侧——这是焦虑症和过度担忧的经典意象。",
          advice:"你最大的恐惧存在于你的头脑中。说出来，它们就会缩小。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:59, name:"宝剑十", nameEn:"Ten of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" rock bottom"," painful ending"," crisis"," betrayal"," inevitable conclusion"],
          uprightMeaning:"触底了。痛苦的结束，但也意味着唯一的方向是向上。最坏的情况已经发生。",
          reversedMeaning:" recovery, survival or resilience.",
          psychologicalInsight:"宝剑十描绘了背部被十把剑穿透的人——这是'触底'(rock bottom)的终极意象。",
          advice:"当你跌到谷底，唯一的出路就是向上。你活下来了，这就是最重要的。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:60, name:"宝剑侍从", nameEn:"Page of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" curiosity"," mental agility"," new ideas"," spy"," alertness"],
          uprightMeaning:"充满好奇心和警觉性的年轻人。新信息的到来，需要保持观察和思考。",
          reversedMeaning:" gossip, deceit or lack of focus.",
          psychologicalInsight:"宝剑侍从代表发展中的人格面貌——好奇、敏锐、善于观察和思考。",
          advice:"保持警惕和好奇。知识就是力量。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:61, name:"宝剑骑士", nameEn:"Knight of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" ambition"," action-speed"," impulsive"," driven"," assertive"],
          uprightMeaning:"快速行动和雄心勃勃的追求者。目标明确，行动迅速，但可能过于冲动。",
          reversedMeaning:" redirected energy, frustration or brute force.",
          psychologicalInsight:"宝剑骑士代表行动迅速、智力驱动的人格类型——优点是果断高效，缺点可能是缺乏深思熟虑。",
          advice:"速度很重要，但方向更重要。确保你在奔向正确的东西。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:62, name:"宝剑王后", nameEn:"Queen of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:[" clarity of thought"," independence"," truth"," directness"," perceptiveness"],
          uprightMeaning:"思想清晰、独立自主的女性形象。能够客观分析情况，说出真相，不被情感左右。",
          reversedMeaning:" coldness, bitterness or emotional cutting off.",
          psychologicalInsight:"宝剑王后代表成熟女性能量的风元素表达——理性、独立、直接且具有洞察力。",
          advice:"真相有时会伤人，但谎言伤得更深。用智慧说出必要的话。",
          symbol:"⚔️", color:"#87CEEB" },
        { id:63, name:"宝剑国王", nameEn:"King of Swords", arcana:"minor", suit:"swords", suitName:"宝剑", element:"风",
          keywords:["intellectual power"," justice"," authority"," truth"," structure"],
          uprightMeaning:"智力和公正的化身。用理性和正义来统治。决策基于事实而非情感。",
          reversedMeaning:" abuse of power, cruelty or rigid thinking.",
          psychologicalInsight:"宝剑国王代表成熟男性能量的风元素表达——理智、公正、权威且有原则。",
          advice:"用智慧来领导，用心来关怀。两者结合才是真正的力量。",
          symbol:"⚔️", color:"#87CEEB" }
    ],

    // 小阿尔卡纳 - 钱币/星币 (土元素) 14张
    pentacles: [
        { id:64, name:"钱币首牌", nameEn:"Ace of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" prosperity"," new financial opportunity"," practicality"," manifestation"," seed of abundance"],
          uprightMeaning:"新的物质机会到来。财务上的好消息、投资机会或实际项目的启动。",
          reversedMeaning:" missed opportunity, financial loss or poor planning.",
          psychologicalInsight:"钱币首牌代表物质世界的丰盛潜能——安全感、稳定性和实际成就的基础。",
          advice:"抓住这个实实在在的机会。丰饶的种子已经种下。",
          symbol:"🪙", color:"#B8860B" },
        { id:65, name:"钱币二", nameEn:"Two of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" balance"," juggling"," adaptability"," time management"," flexibility"],
          uprightMeaning:"需要在多个领域之间保持平衡。灵活适应变化，管理好时间和资源。",
          reversedMeaning:" overwhelm, imbalance or disorganization.",
          psychologicalInsight:"钱币二描绘了一个人玩杂耍——这反映了现代生活中多任务处理和时间管理的挑战。",
          advice:"生活是一场平衡的艺术。学会优雅地同时处理多件事。",
          symbol:"🪙", color:"#B8860B" },
        { id:66, name:"钱币三", nameEn:"Three of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" teamwork"," collaboration"," learning"," implementation"," craftsmanship"],
          uprightMeaning:"团队合作带来成果。学习新技能或在专业领域获得认可。努力工作得到回报。",
          reversedMeaning:" lack of teamwork, poor quality work or mediocrity.",
          psychologicalInsight:"钱币三展示工匠在工作——这代表技能发展、团队合作和专业成长的价值。",
          advice:"好的工作需要合作。你的技能正在被看见和赏识。",
          symbol:"🪙", color:"#B8860B" },
        { id:67, name:"钱币四", nameEn:"Four of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" saving security"," possessiveness"," control"," frugality"," holding on"],
          uprightMeaning:"守住已有的资源。节俭和控制带来安全，但可能过于保守。",
          reversedMeaning:" letting go, spending freely or releasing control.",
          psychologicalInsight:"钱币四显示一个人紧紧抓住钱币——这涉及金钱心理学的主题：安全感与控制欲的关系。",
          advice:"储蓄是明智的，但不要让恐惧阻止你享受生活。",
          symbol:"🪙", color:"#B8860B" },
        { id:68, name:"钱币五", nameEn:"Five of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" hardship"," poverty"," isolation"," worry"," material struggle"],
          uprightMeaning:"面临物质或经济上的困难。可能感到孤立无援，但实际上帮助就在附近。",
          reversedMeaning:" recovery from hardship, finding help or spiritual poverty.",
          psychologicalInsight:"钱币五描绘了两个贫困的人在雪地中行走——这涉及匮乏心态和社会支持的重要性。",
          advice:"即使在最艰难的时候，也不要忘记寻求帮助。教堂的光就在旁边。",
          symbol:"🪙", color:"#B8860B" },
        { id:69, name:"钱币六", nameEn:"Six of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" generosity"," charity"," sharing wealth"," helping others"," balance of giving and receiving"],
          uprightMeaning:"慷慨和分享的时刻。你有能力帮助他人，或者你正在接受他人的帮助。",
          reversedMeaning:" one-sided deals, strings attached or selfishness.",
          psychologicalInsight:"钱币六展示了一个富人在施舍穷人——这涉及给予和接受之间的心理动力学。",
          advice:"财富的意义在于分享。给予和接收同样重要。",
          symbol:"🪙", color:"#B8860B" },
        { id:70, name:"钱币七", nameEn:"Seven of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" patience"," assessment"," investment"," long-term rewards"," perseverance"],
          uprightMeaning:"等待成果成熟的时期。评估你的投资和努力，耐心是关键。",
          reversedMeaning:" impatience, lack of reward or poor investment.",
          psychologicalInsight:"钱币七描绘了一个农夫在等待作物生长——这涉及延迟满足和长期投资的心理过程。",
          advice:"好东西需要时间生长。你的耐心将会得到回报。",
          symbol:"🪙", color:"#B8860B" },
        { id:71, name:"钱币八", nameEn:"Eight of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" craftsmanship"," diligence"," skill development"," hard work"," attention to detail"],
          uprightMeaning:"专注于精进技艺。勤奋工作和持续改进将带来卓越的成果。",
          reversedMeaning:" lack of focus, Mediocrity or cutting corners.",
          psychologicalInsight:"钱币八展示了一个工匠精心雕刻——这代表刻意练习和精通(mastery)追求的心理过程。",
          advice:"卓越是一点一滴积累起来的。专注于你的工艺。",
          symbol:"🪙", color:"#B8860B" },
        { id:72, name:"钱币九", nameEn:"Nine of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" independence"," luxury"," self-sufficiency"," elegance"," financial comfort"],
          uprightMeaning:"通过自己的努力获得的独立和富足。享受劳动成果，优雅而自信。",
          reversedMeaning:" dependence, overspending or living beyond means.",
          psychologicalInsight:"钱币九描绘了一位独立的女性在花园中——这代表自给自足和经济独立带来的心理满足感。",
          advice:"你创造了属于自己的丰盛。享受这份独立带来的自由。",
          symbol:"🪙", color:"#B8860B" },
        { id:73, name:"钱币十", nameEn:"Ten of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" family legacy"," abundance"," inheritance"," long-term success"," prosperity"],
          uprightMeaning:"物质成就和家庭传承的巅峰。家族繁荣、财富积累和代际祝福。",
          reversedMeaning:" family conflict, financial failure or broken legacy.",
          psychologicalInsight:"钱币十描绘了多代人共聚一堂——这代表家庭系统中的财富传递和代际和谐。",
          advice:"真正的财富是可以传承下去的——不仅是金钱，还有智慧和爱。",
          symbol:"🪙", color:"#B8860B" },
        { id:74, name:"钱币侍从", nameEn:"Page of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" diligence"," studiousness"," new opportunity"," reliability"," planning"],
          uprightMeaning:"勤奋好学的年轻人。新的学习或工作机会，踏实可靠的态度。",
          reversedMeaning:" laziness, setbacks or poor planning.",
          psychologicalInsight:"钱币侍从代表发展中的人格面貌——勤奋、务实、愿意学习和成长。",
          advice:"每一步都算数。踏实地朝着你的目标前进。",
          symbol:"🪙", color:"#B8860B" },
        { id:75, name:"钱币骑士", nameEn:"Knight of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:[" efficiency"," routine"," reliability"," methodical"," hard working"],
          uprightMeaning:"可靠、勤奋、方法论的执行者。稳步前进，注重细节和质量。",
          reversedMeaning:" stagnation, rigidity or workaholism.",
          psychologicalInsight:"钱币骑士代表稳重、务实的人格类型——优点是可靠和坚持，缺点可能是缺乏灵活性。",
          advice:"稳扎稳打是一种超能力。信任过程，结果自然会来。",
          symbol:"🪙", color:"#B8860B" },
        { id:76, name:"钱币王后", nameEn:"Queen of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:["nurturing"," practical"," financially secure"," generous"," grounded"],
          uprightMeaning:"既务实又充满关爱的女性形象。善于理财的同时也懂得照顾家人和自己。",
          reversedMeaning:" financial insecurity, neglect of self or smothering.",
          psychologicalInsight:"钱币王后代表成熟女性能量的土元素表达——务实、富有、关爱且脚踏实地。",
          advice:"你可以同时拥有物质丰盛和精神温暖。照顾好自己才能更好地照顾他人。",
          symbol:"🪙", color:"#B8860B" },
        { id:77, name:"钱币国王", nameEn:"King of Pentacles", arcana:"minor", suit:"pentacles", suitName:"钱币", element:"土",
          keywords:["abundance"," success"," enterprise"," stability"," philanthropy"],
          uprightMeaning:"物质成功的顶峰。富有的企业家，既能创造财富也能慷慨分享。",
          reversedMeaning:" greed, stubbornness or materialism.",
          psychologicalInsight:"钱币国王代表成熟男性能量的土元素表达——富有、成功、稳定且具有企业家的远见。",
          advice:"真正的成功不仅在于拥有多少，还在于你能给予多少。",
          symbol:"🪙", color:"#B8860B" }
    ]
};

// 获取所有78张牌
function getAllCards() {
    return [
        ...TAROT_DATA.majorArcana,
        ...TAROT_DATA.wands,
        ...TAROT_DATA.cups,
        ...TAROT_DATA.swords,
        ...TAROT_DATA.pentacles
    ];
}

// 根据ID获取卡牌
function getCardById(id) {
    const allCards = getAllCards();
    return allCards.find(card => card.id === id);
}

// 洗牌算法 (Fisher-Yates)
function shuffleDeck(deck) {
    const shuffled = [...deck];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

// 牌阵配置
const SPREADS = {
    daily: {
        name: "每日一牌",
        cardCount: 1,
        positions: ["今日指引"]
    },
    three: {
        name: "三牌阵",
        cardCount: 3,
        positions: ["过去", "现在", "未来"]
    },
    celtic: {
        name: "凯尔特十字",
        cardCount: 10,
        positions: ["现状", "挑战/阻碍", "潜意识基础", "显意识目标", "过去", "近期未来", "自身态度", "外界影响", "内心希望/恐惧", "最终结果"]
    },
    relationship: {
        name: "关系牌阵",
        cardCount: 2,
        positions: ["你的能量", "对方的能量 / 关系走向"]
    }
};